-- ============================================================
-- Drug Table Creation Script
-- ============================================================
-- Purpose    : Stores one row per unique drug formulation extracted
--              from DrugMasterLinkage. Each RxNorm entry in the
--              source JSONB produces one row here after dosage-form
--              suffix stripping.
--
-- Source     : public."DrugMasterLinkage".combined_clean_jsonb
--                → rxnorm[].generic_formulation
--                → rxnorm[].specific_dosage_form
--                → openfda.drug_info.generic_name
--
-- Related    : drugdb.drug_synonym_formulation  (1:1,    FK → formulation_id)
--              drugdb.drug_ingredient_mapping   (1:many, FK → formulation_id)
--              public."DrugMasterLinkage"       (source, FK → master_linkage_id)
--
-- Population : populate_drug_table.py
-- ============================================================

CREATE TABLE IF NOT EXISTS drugdb.drug (

    -- Unique identifier for each drug formulation.
    -- Generated via uuid.uuid4() in the population script.
    formulation_id      UUID            NOT NULL,

    -- Links this row back to the originating source record in
    -- DrugMasterLinkage. Nullable in case a formulation is added
    -- independently of the linkage table.
    master_linkage_id   UUID            NULL,

    -- Drug generic name as supplied by OpenFDA
    -- (e.g., "quetiapine").
    generic_name        TEXT            NULL,

    -- Formulation string with the dosage-form suffix stripped
    -- (e.g., "quetiapine 100 MG" from "quetiapine 100 MG Oral Tablet").
    -- TEXT (not VARCHAR) — multi-ingredient parenteral nutrition formulations
    -- can exceed 500 chars (observed max 544 in source data).
    generic_formulation TEXT            NULL,

    -- Dosage form type extracted from the same RxNorm entry
    -- (e.g., "Oral Tablet", "Extended Release Oral Tablet").
    dosage_forms        TEXT            NULL,

    CONSTRAINT drug_pkey PRIMARY KEY (formulation_id)
);

-- ── Foreign key ──────────────────────────────────────────────
-- Reference back to the source linkage record.
-- ON DELETE CASCADE removes formulations if the parent linkage
-- row is deleted.
ALTER TABLE drugdb.drug
    DROP CONSTRAINT IF EXISTS drug_master_linkage_fkey;

ALTER TABLE drugdb.drug
    ADD CONSTRAINT drug_master_linkage_fkey
    FOREIGN KEY (master_linkage_id)
    REFERENCES public."DrugMasterLinkage" (master_linkage_id)
    ON DELETE CASCADE;

-- ── Indexes ───────────────────────────────────────────────────

-- Speeds up joins from drug_synonym_formulation and
-- drug_ingredient_mapping back to their source linkage record.
CREATE INDEX IF NOT EXISTS idx_drug_master_linkage_id
    ON drugdb.drug (master_linkage_id);

-- Supports free-text and prefix searches on generic name.
CREATE INDEX IF NOT EXISTS idx_drug_generic_name
    ON drugdb.drug (generic_name);

-- Composite index used by populate_drug_synonym_formulation.py
-- and populate_drug_ingredient_mapping.py to resolve formulation_id
-- from (generic_formulation, dosage_forms) during population.
CREATE INDEX IF NOT EXISTS idx_drug_formulation_dosage
    ON drugdb.drug (generic_formulation, dosage_forms);

-- ── Column comments ───────────────────────────────────────────
COMMENT ON TABLE drugdb.drug IS
    'One row per unique drug formulation extracted from DrugMasterLinkage.combined_clean_jsonb. Populated by populate_drug_table.py.';

COMMENT ON COLUMN drugdb.drug.formulation_id IS
    'Primary key. UUID generated by populate_drug_table.py via uuid.uuid4().';

COMMENT ON COLUMN drugdb.drug.master_linkage_id IS
    'FK to public."DrugMasterLinkage".master_linkage_id. Links the formulation back to its originating source record.';

COMMENT ON COLUMN drugdb.drug.generic_name IS
    'Generic drug name from combined_clean_jsonb → openfda → drug_info → generic_name (e.g., "quetiapine").';

COMMENT ON COLUMN drugdb.drug.generic_formulation IS
    'RxNorm generic_formulation with the dosage_form suffix stripped (e.g., "quetiapine 100 MG"). Used as a lookup key during child-table population.';

COMMENT ON COLUMN drugdb.drug.dosage_forms IS
    'Dosage form from rxnorm[].specific_dosage_form (e.g., "Oral Tablet"). Paired with generic_formulation to uniquely identify a formulation.';
